Repository UBC-MDS/pypuck, pull requests merged in 2020-02, with the labels that each got.

#7 Added all of the project structure from cookie-cutter and poetry
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  .readthedocs.yml
  CONDUCT.md
  CONTRIBUTING.md
  CONTRIBUTORS.md
  LICENSE
  README.md
  docs/Makefile
  docs/conf.py
  docs/contributing.rst
  docs/contributors.rst
  docs/index.rst
  docs/installation.rst
  docs/make.bat
  docs/readme.rst
  docs/usage.rst
  pyproject.toml
  pypuck/__init__.py
  pypuck/pypuck.py
  tests/__init__.py
  tests/test_pypuck.py
Labels: group

#17 Added player_stats feature/function
  LICENSE
  README.md
  docs/installation.rst
  docs/source/modules.rst
  docs/source/pypuck.rst
  poetry.lock
  pyproject.toml
  pypuck/pypuck.py
Labels: enhancement

#18 define a new function and add its docstring
  README.md
  pypuck/pypuck.py
Labels: documentation, individual

#20 build docstring `attendance` and add its description on README
  .DS_Store
  README.md
  docs/.DS_Store
Labels: individual

#21 Update pypuck.py and finalize Readme
  README.md
  pypuck/pypuck.py
Labels: enhancement
