Repository UBC-MDS/pypuck, pull requests merged in 2020-03, with the labels that each got.

#28 Draft pick
  pypuck/pypuck.py
Labels: enhancement, individual

#29 Player stats feature
  pypuck/helpers/helpers.py
  pypuck/pypuck.py
  tests/test_pypuck.py
Labels: enhancement, individual

#33 Add output functions to draft_pick
  tests/test_pypuck.py
Labels: enhancement

#34 Attendance function and tests done
  .DS_Store
  pypuck/.DS_Store
  pypuck/pypuck.py
  tests/test_pypuck.py
Labels: enhancement, individual

#37 added coverage and dependencies
  pyproject.toml
Labels: documentation

#38 Added project dependencies and tested code coverage.
  pyproject.toml
Labels: documentation

#40 update attendance description on README & test docstring
  README.md
  pypuck/pypuck.py
  tests/test_pypuck.py
Labels: documentation, individual

#48 modify attendance documentation
  pypuck/pypuck.py
Labels: documentation, enhancement

#51 Continuous integration
  .github/workflows/build.yml
  .github/workflows/release.yml
  poetry.lock
  pyproject.toml
Labels: enhancement

#62 Minor formatting change
  README.md
  pyproject.toml
  pypuck/__init__.py
Labels: enhancement
